service: graduation-serverless
frameworkVersion: '3'

plugins:
  -serverless-webpack

package: 
  individually: true  

provider:
  name: aws
  runtime: nodejs18.x
  profile: MeAnkan
  region: eu-north-1
  iam: 
    role: arn:aws:iam::013575884800:role/XteamLambdaRole

functions:
  lambdaGetImages:
    handler: lambda-functions/LambdaGetImages.handler
    events:
      - httpApi:
          path: /xteam/images
          method: GET

  lambdaGetImageId:
    handler: lambda-functions/LambdaGetImageId.handler
    events: 
      - httpApi: 
          path: /xteam/images/{imageId}
          method: GET

  lambdaPostImage:
    handler: lambda-functions/LambdaPostImage.handler
    events:
      - httpApi:
          path: /xteam/images
          method: PUT

  lambdaDeleteImage:
    handler: lambda-functions/LambdaDeleteImageId.handler
    events:
      - httpApi:
          path: /xteam/images/{imageId}
          method: DELETE


resources: 
  Resources: 
  # Image Table
    ImageTable: 
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain 
      Properties: 
        TableName: ImageTable
        AttributeDefinitions: 
          - AttributeName: "PK"
            AttributeType: "S"
          - AttributeName: "imageId"
            AttributeType: "S"
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification: 
          PointInTimeRecoveryEnabled: false
        KeySchema: 
          - AttributeName: "PK"
            KeyType: HASH
          - AttributeName: "imageId"
            KeyType: RANGE